repos:
- repo: local
  hooks:
    - id: black-check
      name: black-check
      entry: black .
      language: system
      types: [ python ]
    - id: pylint-check
      name: pylint-check
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "--ignore-paths",
          "tests/",
          "--disable=C0114", # Remove temporarily docstring
          "--disable=C0115", # Remove temporarily docstring
          "--disable=C0116", # Remove temporarily docstring
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: pytest-unit-check
      name: pytest-unit-check
      entry: pytest -m unit
      language: system
      types: [ python ]
      pass_filenames: false
